name: Java CI with Maven and JFrog Artifactory

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        cache: maven
        java-version: '11'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Install xmlstarlet
      run: sudo apt-get -y install xmlstarlet

    - name: Extract GAV coordinates from POM using xmllint
      run: |
        group_id=$(xmllint --xpath "string(/project/groupId)" pom.xml)
        artifact_id=$(xmllint --xpath "string(/project/artifactId)" pom.xml)
        version=$(xmllint --xpath "string(/project/version)" pom.xml)
        repo_path="${group_id//.//}/$artifact_id/$version"
        export ARTIFACT_PATH="${group_id//.//}/$artifact_id/$version"
        echo "Repository Path: $ARTIFACT_PATH"
      working-directory: ${{ github.workspace }}

    - uses: jfrog/setup-jfrog-cli@v3
    - name: Publish to JFrog Artifactory
      run: |
        jf c add acme-artifactory \
         --url ${{ secrets.JF_URL }} \
         --user ${{ secrets.JF_USER }} \
         --password ${{ secrets.JF_PASSWORD }}
      
        jf rt u "target/*.jar" "libs-release-local/$ARTIFACT_PATH"
      env:
        JF_URL: ${{ secrets.JF_URL }}
        JF_USER: ${{ secrets.JF_USER }}
        JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
        JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
