name: Java CI with Maven and JFrog Artifactory

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        cache: maven
        java-version: '11'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Install xmlstarlet
      run: sudo apt-get -y install xmlstarlet

    - name: Extract GAV coordinates from POM using xmlstarlet
      run: |
        group_id=$(xmlstarlet sel -N ns=http://maven.apache.org/POM/4.0.0 -t -v "//ns:project/ns:groupId" pom.xml)
        artifact_id=$(xmlstarlet sel -N ns=http://maven.apache.org/POM/4.0.0 -t -v "//ns:project/ns:artifactId" pom.xml)
        version=$(xmlstarlet sel -N ns=http://maven.apache.org/POM/4.0.0 -t -v "//ns:project/ns:version" pom.xml)
        ARTIFACT_PATH="${group_id//.//}/$artifact_id/$version"
        echo "Repository Path: $ARTIFACT_PATH"
        echo "::set-output name=ARTIFACT_PATH::$ARTIFACT_PATH"  # Set an output for subsequent steps
      working-directory: ${{ github.workspace }}


    - uses: jfrog/setup-jfrog-cli@v3
    - name: Publish to JFrog Artifactory
      run: |
        jf c add acme-artifactory \
         --url ${{ secrets.JF_URL }} \
         --user ${{ secrets.JF_USER }} \
         --password ${{ secrets.JF_PASSWORD }}
    
        echo "${{ steps.extract-gav.outputs.ARTIFACT_PATH}}"
        jf rt u "*.jar" "libs-release-local/${{ steps.extract-gav.outputs.ARTIFACT_PATH}}"
      env:
        JF_URL: ${{ secrets.JF_URL }}
        JF_USER: ${{ secrets.JF_USER }}
        JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
        JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
