name: Java CI with Maven and JFrog Artifactory

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        cache: maven
        java-version: '11'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Install xmlstarlet
      run: sudo apt-get -y install xmlstarlet

    - name: Extract GAV coordinates from POM
      run: |
        GROUP_ID=$(xmlstarlet sel -t -v "//project/groupId" pom.xml)
        ARTIFACT_ID=$(xmlstarlet sel -t -v "//project/artifactId" pom.xml)
        VERSION=$(xmlstarlet sel -t -v "//project/version" pom.xml)
        REPO_PATH="${GROUP_ID//.//}/$ARTIFACT_ID/$VERSION/"
        echo "Repository Path: $REPO_PATH"
      working-directory: ${{ github.workspace }}
      env:
        XMLSTARLET_SKIP: "1"

    - uses: jfrog/setup-jfrog-cli@v3
    - name: Publish to JFrog Artifactory
      run: |
        jfrog rt config acme-artifactory \
          --url ${{ secrets.JF_URL }} \
          --user ${{ secrets.JF_USER }} \
          --password ${{ secrets.JF_PASSWORD }} \
          --access-token ${{ secrets.JF_ACCESS_TOKEN }}
        
        jfrog rt mvn-publish target/*.jar acme-artifactory/lib-release/$REPO_PATH
      env:
        JF_URL: ${{ secrets.JF_URL }}
        JF_USER: ${{ secrets.JF_USER }}
        JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
        JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
